export const START_SEARCH_PROCESS = 'START_SEARCH_PROCESS';
export const STOP_SEARCH_PROCESS = 'STOP_SEARCH_PROCESS';
export const UPDATE_SEARCH_ID = 'UPDATE_SEARCH_ID';
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
